### ISSUE TITLE
Unable to launch

### ISSUE THREAD

**Issue by carcarlo** [Percona-Lab/mysql_random_data_load#19]
On Ubuntu 16.04.4 LTS I get the following error. What's wrong?
I've installed go even if in the documentation is not mandatory.

panic: invalid argument to Int63n

goroutine 1 [running]:
math/rand.(*Rand).Int63n(0xc420066180, 0x8000000000000000, 0x3fc408d2ac22c4d3)
	/usr/local/go/src/math/rand/rand.go:108 +0x10d
math/rand.Int63n(0x8000000000000000, 0x16a)
	/usr/local/go/src/math/rand/rand.go:267 +0x37
github.com/Percona-Lab/mysql_random_data_load/internal/getters.(*RandomDecimal).Value(0xc42028c060, 0xc42010e180, 0xc42010e2d7)
	/home/karl/golang/src/github.com/Percona-Lab/mysql_random_data_load/internal/getters/decimal.go:17 +0x85
github.com/Percona-Lab/mysql_random_data_load/internal/getters.(*RandomDecimal).String(0xc42028c060, 0xc42010e180, 0x16a)
	/home/karl/golang/src/github.com/Percona-Lab/mysql_random_data_load/internal/getters/decimal.go:22 +0x2f
github.com/Percona-Lab/mysql_random_data_load/internal/getters.(*RandomDecimal).Quote(0xc42028c060, 0xc420084580, 0x155)
	/home/karl/golang/src/github.com/Percona-Lab/mysql_random_data_load/internal/getters/decimal.go:26 +0x2b
main.run(0xc420011720, 0xc4200f2400, 0xc4200f2800, 0xc420020150, 0xc42028e000, 0x1c, 0x20, 0x1, 0xa, 0x807790, ...)
	/home/karl/golang/src/github.com/Percona-Lab/mysql_random_data_load/main.go:251 +0x1bc
main.main()
	/home/karl/golang/src/github.com/Percona-Lab/mysql_random_data_load/main.go:189 +0xbb4

**Comment by guriandoro** [comment]
Hi,

Can you please post the following information?

- mysql_random_data_load version used
- mysql version
- exact command used
- SHOW CREATE TABLE for the table you are trying to insert data on


Thanks.

**Comment by timhughes** [comment]
Duplicate of #24
